Enhancement/issue 5 docker workflow
NewportDataProject/data-night pull request #8
Opened 2017-12-31 17:54 UTC by thescientist13

resolves #5 and some of #2 

1. Added a Dockerfile that is based on 
- Debian Linux
- Anaconda w/ Python3
- Jupyter
1. Added general stack documentation to the README
1. Added Docker specific instructions and example workflow

2017-12-31 18:08 UTC, paulopperman commented
one thing we may have to do is get data into the container from the web or external source.  what would the workflow for that look like?

2017-12-31 18:30 UTC, paulopperman requested changes
I wasn't able to get to the jupyter server running on the container from my local browser (kept getting connection reset error).  I think you need to do some additional configuration of the jupyter notebook server to allow external connections.

http://jupyter-notebook.readthedocs.io/en/stable/public_server.html

2017-12-31 18:30 UTC, paulopperman commented on Dockerfile
> +FROM continuumio/anaconda3:5.0.1
This should either clone the repo from github, or build from the local directory so we have things prepopulated.

2017-12-31 18:34 UTC, thescientist13 commented
Good question!

Via a web source, just use something like `wget` when in the container.  For general purpose file access, likely it's just a simple matter of mounting some sort of "data" directory in the repo to the container, which can then be accessed via the container using a volume.
https://docs.docker.com/engine/admin/volumes/volumes/

I will get an example of that in this PR.

2017-12-31 18:34 UTC, thescientist13 commented on Dockerfile
> +FROM continuumio/anaconda3:5.0.1
not sure what you mean here?

2017-12-31 18:38 UTC, thescientist13 commented
@paulopperman 
> I wasn't able to get to the jupyter server running on the container from my local browser (kept getting connection reset error). I think you need to do some additional configuration of the jupyter notebook server to allow external connections.

I hadn't included the hub feature as part of this effort, just the notebook as I thought we were just going to use [jupyterhub-deploy-docker](https://github.com/jupyterhub/jupyterhub-deploy-docker) on a droplet?

Can you confirm if running notebook worked for you though?

2017-12-31 18:55 UTC, paulopperman commented
@thescientist13 the issue is from following the README instructions to launch jupyter notebook.  the container runs fine, but couldn't get a browser to connect to the server.  i'll show my workaround on the file.

2017-12-31 18:56 UTC, paulopperman commented on README.md
> +1. Now you can connect to your container via a shell `docker run -p 8888:8888 -it sandbox`
fix the container name, and map a different port to avoid conflicting with a local jupyter server:
`docker run -p 8889:8888 -it data-night`

2017-12-31 19:02 UTC, paulopperman commented on README.md
> +:/# jupyter notebook --ip=127.0.0.1 --allow-root
@thescientist13 i had to do thre things to get this to work:
1. 
```# jupyter notebook --generate-config --allow-root```

2.
edit `~/.jupyter/jupyter_notebook_config.py` to change `c.NotebookApp.ip = '*'`

3.
from home, run `jupyter notebook --allow-root`

after that, i can get to the notebook server from my local machine

2017-12-31 21:35 UTC, thescientist13 commented on README.md
> +:/# jupyter notebook --ip=127.0.0.1 --allow-root
hmm, curious, what was the error / console output was that you had when running
```shell
jupyter notebook --ip=127.0.0.1 --allow-root
```
?

2017-12-31 21:40 UTC, paulopperman commented on README.md
> +:/# jupyter notebook --ip=127.0.0.1 --allow-root
No console error. Browser error (connection refused)

2017-12-31 21:55 UTC, thescientist13 commented on README.md
> +:/# jupyter notebook --ip=127.0.0.1 --allow-root
i see.  I just realized i had the jupyter server from yesterday still running and might have been connecting to that inadvertently.  Trying my steps over, which will likely me see me reproducing what you saw.

2017-12-31 22:12 UTC, thescientist13 commented
@paulopperman 
I updated the Docker steps and updated the issue description with TODOs.  Shouldn't be much more effort to get this all wired up nice-nice.

2017-12-31 23:47 UTC, davenamin reviewed
this looks good! was able to follow all the steps with Docker on Windows, but one hiccup and one suggestion:

the line "And visit the generated URL after the server starts" isn't quite right, because trying to navigate to 0.0.0.0 on the host fails. It does work if I manually change it to 127.0.0.1:8889...blahblahblah, but I have a suggestion...

why not put the "jupyter notebook --ip=...." command into the Dockerfile explicitly? given, that wouldn't work so well with the default random token needed to log into the notebook, but setting a default password might make things a lot easier. that would require creating a configuration file (like what @paulopperman had suggested when running into the IP address issue) but would simplify things for someone who isn't familiar with Docker or CLI usage. the configuration file can be checked into the repo and ADDed into the Docker container during the build steps.

2017-12-31 23:51 UTC, thescientist13 commented
@davenamin 
Thanks for the reviewing and providing feedback!  

> "And visit the generated URL after the server starts" isn't quite right, because trying to navigate to 0.0.0.0 on the host fails. It does work if I manually change it to 127.0.0.1:8889...blahblahblah, but I have a suggestion...

Ah, good find.  Maybe `0.0.0.0` presents an issue on Windows, will see if `127.0.0.1` works even if binding to `0.0.0.0` when starting Jupyter Notebook.

> why not put the "jupyter notebook --ip=...." command into the Dockerfile explicitly?

Agreed!  That's my next task with this PR.  (You can see what I plan to do specifically in item #2 from TODO section of this PR description)

2018-01-01 00:07 UTC, davenamin commented
> Ah, good find. Maybe 0.0.0.0 presents an issue on Windows, will see if 127.0.0.1 works even if binding to 0.0.0.0 when starting Jupyter Notebook.

Sorry, wasn't very specific with my language: binding to 0.0.0.0 definitely works on Windows (and I'd guess OSX and Linux) but when the `jupyter notebook --ip=0.0.0.0 --port 8889 --allow-root` command finishes and prints the URL to use, that URL isn't actually valid because it contains the wildcard IP. The README says:

>And visit the generated URL after the server starts, e.g. http://0.0.0.0:8889/?token=39f8a00b806723e69e34ce0c471165100453f3f8f80a2126

but after pasting the generated URL into a browser, it won't work until the beginning IP is changed to 127.0.0.1 (or `localhost`).

2018-01-01 00:22 UTC, paulopperman commented
I'm offline, but earlier, for the IP, I could just go to localhost:8888 on
my machine to get to the notebook. I didn't run the server with the IP
specified though.

On Dec 31, 2017 7:07 PM, "davenamin" <notifications@github.com> wrote:

> Ah, good find. Maybe 0.0.0.0 presents an issue on Windows, will see if
> 127.0.0.1 works even if binding to 0.0.0.0 when starting Jupyter Notebook.
>
> Sorry, wasn't very specific with my language: binding to 0.0.0.0
> definitely works on Windows (and I'd guess OSX and Linux) but when the jupyter
> notebook --ip=0.0.0.0 --port 8889 --allow-root command finishes and
> prints the URL to use, that URL isn't actually valid because it contains
> the wildcard IP. The README says:
>
> And visit the generated URL after the server starts, e.g.
> http://0.0.0.0:8889/?token=39f8a00b806723e69e34ce0c471165
> 100453f3f8f80a2126
>
> but after pasting the generated URL into a browser, it won't work until
> the beginning IP is changed to 127.0.0.1 (or localhost).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NewportDataProject/data-night/pull/8#issuecomment-354629280>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGAeGkC16Ttu6M5bC2xckfPniaIfm7Uuks5tGCGlgaJpZM4RP5zx>
> .
>

2018-01-01 17:01 UTC, thescientist13 commented on docker-compose.yml
> +    command: tail -F anything
@paulopperman / @davenamin 
not sure if we would want to make `jupyter` the default running process?

2018-01-01 17:05 UTC, thescientist13 commented
@paulopperman / @davenamin 
Please review, I've made some pretty big updated that I think brings this pretty to close to ready for prime time!  

Here a summary of my latest changes (full list tracked in the description)
> 3. Added Docker specific instructions and example workflow _(using docker-compose)_
> 4. Version controlled a configuration file for the Jupyter Notebook server
> 5. Created a _workspace_ directory that can be used as a two-way mount point between the host and container
> 6. Make _workspace_ the working directory, where "starter" Jupyter Notebooks for contributors can be saved, for example

Essentially, this workspace directory can be where example Notebooks can be committed (like in #7 ) and it is also two-way mounted so whatever the user saves, will be tracked in `git` on their host machine.

Only TODO item remaining is the IP Address discrepancy between OSX / Windows, but I don't see it as a showstopper.
> Try and fix the 0.0.0.0 / 127.0.0.0 issue between OSX / Windows when loading the Jupyter Notebook server from the host

Let me know what you think, thanks for all the good feedback!

2018-01-01 20:29 UTC, paulopperman commented
ok, so i did some tweaking of the config file to remove security altogether (not recommended for anything in the wild.)  it works for me by going to `localhost:8889` as expected.  i also think that kicking off the server with jupyter running is a good idea, to keep the bar to entry low.  people can still `/bin/bash` if they want.

2018-01-01 21:57 UTC, davenamin commented
hey @thescientist13 @paulopperman this looks really good! i tried it both with Owen's branch and then with Paul's changes. I agree with Paul's changes - it's definitely a lot easier to get everything going when the notebook automatically starts up and doesn't need any password.

I do have a question though: why does the docker-compose file create two containers? I was able to delete both the Dockerfile from the repository as well as the "sandbox" container in the docker-compose.yml and it worked just fine. Alternatively, if the plan is to install python packages as part of the Docker container build, maybe the "python" container in the docker-compose.yml should contain the line `build: .` instead of `image: continuumio/anaconda3:5.0.1`

2018-01-01 22:16 UTC, paulopperman commented
@davenamin i just pushed a commit to #9 that uses the newportdata/datanight_python image, which is built from the dockerfile in the repo and includes the python dependencies.  dockerfile is redundant for now, and we may want to move it to its own repo at some point in the future.

2018-01-01 22:25 UTC, paulopperman approved these changes

2018-01-01 22:45 UTC, merged

2018-01-02 01:17 UTC, thescientist13 commented on README.md
> +**Note: For windows, use http://127.0.0.0:8889?/token=xxx**
@paulopperman / @davenamin 
Can this be removed now?

2018-01-02 01:25 UTC, thescientist13 commented
@paulopperman 
> also, i also just tested without sandbox (maybe that was a testing image?) and it worked fine for me. i'm going to delete it in my branch and merge to this one.

Yeah, might have been pre-emptive, but it was mainly just trying to leverage `docker-compose` for what it does best, starting up a bunch of containers so they can talk to each other, like if wanted to add a database, like in [the example](https://hub.docker.com/u/thescientist/) I referenced in the description.

2018-01-02 01:44 UTC, thescientist13 commented on docker-compose.yml
> +    image: newportdata/datanight_python:initial
nice 🎉

2018-01-02 05:29 UTC, paulopperman commented on README.md
> +**Note: For windows, use http://127.0.0.0:8889?/token=xxx**
yeah.  issue #13 opened for this and some other stuff.